spring:
  application:
    name: gateway-service
    
  cloud:
    gateway:
      routes:
      - id: employee-service
        uri: http://localhost:3030/
        predicates:
        - Path= /api/v1/employees/**
      - id: score-service
        uri: lb://SCORE-SERVICE 
        predicates: 
        - Path= /api/v1/scores/** 

management:
  endpoints:
    web:
      exposure:
        include:
        - "*"                